### ISSUE TITLE
Для это есть более лаконичная замена

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson2#1]
https://github.com/Ir4D/lesson2/blob/e004c4e01121690ca47e0ac1b7ebf6cb942e595d/while_ask.py#L11

Твой код рабочий, но можно более лаконично проверить есть ли значение в словаре:

`if user_question in my_dict:`

**Comment by Ir4D** [comment]
https://github.com/Ir4D/lesson2/blob/e697413eb80735eaf78ea371d7f56bf6c98d80b1/while_ask.py#L11

Ок! Обновила файл
