### ISSUE TITLE
В питоне можно считать сумму списка одной функцией

### ISSUE THREAD

**Issue by DanaZL** [Ir4D/lesson2#2]
https://github.com/Ir4D/lesson2/blob/e004c4e01121690ca47e0ac1b7ebf6cb942e595d/for_scores.py#L26

Все круто! На будущее может быть полезно считать сумму списка одной функцией
Попробуй сделать` sum(classes['scores'])`

**Comment by Ir4D** [comment]
https://github.com/Ir4D/lesson2/blob/ec5d95c6083cc6b4cafaa6370d5f2b6cf1047075/for_scores.py#L12
https://github.com/Ir4D/lesson2/blob/ec5d95c6083cc6b4cafaa6370d5f2b6cf1047075/for_scores.py#L13
https://github.com/Ir4D/lesson2/blob/ec5d95c6083cc6b4cafaa6370d5f2b6cf1047075/for_scores.py#L23
Дополнила код функцией sum и избавилась от вложенных for - кажется, даже чуть аккуратнее стало выглядеть)
